name: DT_CUnit
on:
  push:
     branches:
       - ci

jobs:
  build-linux:
    name: 'On Linux'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: 'Package installations'
        shell: bash
        run: |
          sudo apt update
          sudo apt install libcunit1-dev 
      - name: 'Compiling'
        run:  |
          mkdir Build
          cd Build
          cmake ..
          make
       - name: 'Testing'
        run:  |
          cd Build
          make test
